### ISSUE TITLE
KeyError: 'scaffold00001' 

### ISSUE THREAD

**Issue by JonEilers** [uio-cels/NucDiff#18]
Tried running nucdiff with a delta file from mummer4. The below error was returned. 

command
```bash
nucdiff --delta_file /home/jon/Working_Files/mummer/genome_assembly_comparison/ajap_pcali-plat/ajap2plat.delta \
		--proc 5 \
		 /home/jon/Working_Files/mummer/genome_assembly_comparison/ajap_pcali-plat/ajap_assembly.fa \
		 /home/jon/Working_Files/mummer/genome_assembly_comparison/genome_assemblies/pcali_genome.platanus.fa \
		 /home/jon/Working_Files/mummer/genome_assembly_comparison/ajap_pcali-plat \
		 ajap2plat
```
Returned error 
```bash
Traceback (most recent call last):
  File "/home/jon/anaconda3/envs/nucdiff/bin/nucdiff", line 6, in <module>
    from nucdiff.nucdiff import main
  File "/home/jon/anaconda3/envs/nucdiff/lib/python3.8/site-packages/nucdiff/nucdiff.py", line 103, in <module>
    main()
  File "/home/jon/anaconda3/envs/nucdiff/lib/python3.8/site-packages/nucdiff/nucdiff.py", line 101, in main
    START(args)
  File "/home/jon/anaconda3/envs/nucdiff/lib/python3.8/site-packages/nucdiff/nucdiff.py", line 58, in START
    struct_dict,end_err_dict,unmapped_list,uncovered_dict=FIND_ERRORS_ASSEMBLY(file_ref,file_contigs, working_dir, nucmer_opt, prefix,proc_num, filter_opt,delta_file,reloc_dist,coord_file ) #class Errors
  File "/home/jon/anaconda3/envs/nucdiff/lib/python3.8/site-packages/nucdiff/find_errors.py", line 33, in FIND_ERRORS_ASSEMBLY
    nuc.FIND_ERR_INSIDE_FRAG(proc_num,file_contigs)
  File "/home/jon/anaconda3/envs/nucdiff/lib/python3.8/site-packages/nucdiff/class_nucmer.py", line 185, in FIND_ERR_INSIDE_FRAG
    seq=contigs_dict[cont_name][start_seq-1 :end_seq-1   +1]
KeyError: 'scaffold00001'
```

**Comment by kseniakh** [comment]
What is the full name of scaffold00001 in the input fasta file?

**Comment by JonEilers** [comment]
First scaffold of ajap_assembly.fa 
>MRZV01000001.1 Apostichopus japonicus isolate Shaxun AJAPscaffold1, whole genome shotgun sequence

First scaffold of pcali_genome.platanus.fa 
>scaffold1_len39543_cov136.241_read142_maxK110

**Comment by kseniakh** [comment]
The problem is that the names of sequences in pcali_genome.platanus.fa don't correspond to the names in the delta files. Check carefully what you have done to generate delta file. The names in both files should be the same. There can be one exception, when names in delta files are shorted because of space symbol  in the sequence names, but NucDiff handles such situations.
